Various Updates
center-for-threat-informed-defense/adversary_emulation_library pull request #57
Opened 2021-01-26 13:37 UTC by jwbaker-mitre

Various updates and edits.

- Created /structure folder for housing all structural documentation and examples
- Created APT29 /YAML folder for housing alternative community produced YAML files, similar to FIN6 plan.
- Corrected several hyperlink references, dates, and formatting issues

2021-01-26 14:05 UTC, MarkDavidson requested changes
Do you have a way to make the title more accurate while keeping it short? If not, that's OK.

2021-01-26 14:16 UTC, jwbaker-mitre commented on apt29/NOTICE.txt
> +Copyright 2021 MITRE Engenuity. Approved for public release. Document number AT0008.
Agreed on the date range, however we should ask @jonathanbaker on this one.

2021-01-26 20:30 UTC, jwbaker-mitre commented on apt29/Emulation_Plan/YAML/README.md
> +
1. The directory is now lowercase.
2. YAML file for each plan is now contained within the respective yaml folder.  I had to check to ensure this did not break any plugin functionality with the CALDERA team, and it does not.
3. The placeholder has now been replaced with the initial emulation plan yaml entry.

2021-01-26 20:38 UTC, jwbaker-mitre commented on structure/format_dictionary.yaml
> +    adversary_name: Adversary
@MarkDavidson I like the use of angle brackets, however nearly every field on this format_dictionary is a variable.  Do you think we should proceed with encapsulating all of them in brackets or leaving them as they currently are?

2021-01-27 18:02 UTC, jwbaker-mitre commented on apt29/NOTICE.txt
> +Copyright 2021 MITRE Engenuity. Approved for public release. Document number AT0008.
Based on Frank's concurrence as well, I've changed the overall library to include 2021.  The individual plans still hold the copyright date of the year of their release respectively.  https://github.com/center-for-threat-informed-defense/adversary_emulation_library/pull/57/commits/4be17d4d651fe792a1dc6f3e950a18ddbc8dbeea

2021-01-28 13:04 UTC, MarkDavidson commented on structure/format_dictionary.yaml
> +    adversary_name: Adversary
@jwbaker-mitre I'll leave it to your judgement. The result should be whatever is best for the author of a new emulation plan.

2021-01-28 13:32 UTC, jwbaker-mitre commented on structure/format_dictionary.yaml
> +    adversary_name: Adversary
I am going to leave it in its current state and we can revisit at a later time.

2021-02-02 20:10 UTC, MarkDavidson approved these changes

2021-02-02 20:10 UTC, merged